[package]
name = "penumbra-transaction"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace deps
decaf377-ka = { path = "../decaf377-ka/" }
decaf377-fmd = { path = "../decaf377-fmd/" }
penumbra-proto = { path = "../proto/" }
penumbra-crypto = { path = "../crypto/" }
penumbra-tct = { path = "../tct" }
penumbra-proof-params = { path = "../proof-params/" }

# Git deps
decaf377 = { git = "https://github.com/penumbra-zone/decaf377" }
decaf377-rdsa = { git = "https://github.com/penumbra-zone/decaf377-rdsa" }
poseidon377 = { git = "https://github.com/penumbra-zone/poseidon377", rev = "a2d8c7a3288e2e877ac88a4d8fd3cc4ff2b52c04" }
ibc = "0.23.0"
ibc-proto = { version = "0.22.0", features = ["std"] }


# Crates.io deps
ark-ff = "0.3"
ark-serialize = "0.3"
regex = "1.5"
sha2 = "0.9"
bech32 = "0.8.1"
fpe = "0.5"
aes = "0.7"
anyhow = "1"
thiserror = "1"
bytes = "1"
derivative = "2.2"
hex = "0.4"
blake2b_simd = "0.5"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
once_cell = "1.8"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
chacha20poly1305 = "0.9.0"
prost-types = "0.11"
pbjson-types = "0.5"
# only needed because ark-ff doesn't display correctly
num-bigint = "0.4"
serde_json = "1"
tracing = "0.1"

[dev-dependencies]
proptest = "1"
proptest-derive = "0.3"
serde_json = "1"
